// 第三方接口请求封装 - douyin
// 基于MaxHub API中转站调用，包含所有API

const config = require('../config.json');
const BASE_URL = config.apiBase.url;
const AUTH_HEADER = config.apiBase.authHeader;
const AUTH_ENV_NAME = config.apiBase.authEnvVar;

function resolveCredential() {
  const proc = typeof process !== 'undefined' ? process : {};
  const env = proc.env || {};
  return env[AUTH_ENV_NAME] || '';
}
const PLATFORM = 'douyin';

/**
 * 通用API请求方法
 * @param {string} path - API路径
 * @param {object} params - 请求参数
 * @param {string} method - 请求方法 GET/POST
 * @returns {Promise<object>} API响应数据
 */
async function request(path, params = {}, method = 'GET') {
  const url = `${BASE_URL}${path}`;
  const headers = {
    [AUTH_HEADER]: resolveCredential(),
    'Content-Type': 'application/json',
  };
  const options = { method, headers };
  if (method === 'GET') {
    const query = new URLSearchParams(params).toString();
    const fullUrl = query ? `${url}?${query}` : url;
    const response = await fetch(fullUrl, options);
    return handleResponse(response);
  }
  options.body = JSON.stringify(params);
  const response = await fetch(url, options);
  return handleResponse(response);
}

/**
 * 处理API响应
 */
async function handleResponse(response) {
  const data = await response.json();
  if (response.status === 401) throw new Error('API Key无效或未配置，请访问 https://www.aconfig.cn 创建API Key');
  if (response.status === 402) throw new Error('账户余额不足，请访问 https://www.aconfig.cn 充值');
  if (response.status === 429) throw new Error('请求频率超限，请等待30秒后重试');
  if (!response.ok) throw new Error(data.message || `请求失败: ${response.status}`);
  return data;
}

const API_REGISTRY = {
  // web
  fetchOneVideoDanmaku: { path: '/web/fetch_one_video_danmaku', params: ['item_id', 'duration', 'end_time', 'start_time'] },
  fetchHomeFeed: { path: '/web/fetch_home_feed' },
  fetchRelatedPosts: { path: '/web/fetch_related_posts', params: ['aweme_id'] },
  fetchUserCollectionVideos: { path: '/web/fetch_user_collection_videos', method: 'POST' },
  fetchUserCollects: { path: '/web/fetch_user_collects', method: 'POST' },
  fetchUserCollectsVideos: { path: '/web/fetch_user_collects_videos', params: ['collects_id'] },
  fetchUserMixVideos: { path: '/web/fetch_user_mix_videos', params: ['mix_id'] },
  fetchUserLiveVideos: { path: '/web/fetch_user_live_videos', params: ['webcast_id'] },
  fetchUserLiveVideosBySecUid: { path: '/web/fetch_user_live_videos_by_sec_uid', params: ['sec_uid'] },
  fetchUserLiveVideosByRoomId: { path: '/web/fetch_user_live_videos_by_room_id', params: ['room_id'] },
  fetchUserLiveVideosByRoomIdV2: { path: '/web/fetch_user_live_videos_by_room_id_v2', params: ['room_id'] },
  fetchLiveRoomProductResult: { path: '/web/fetch_live_room_product_result', params: ['room_id', 'author_id'] },
  fetchProductDetail: { path: '/web/fetch_product_detail', params: ['product_id'] },
  fetchProductSkuList: { path: '/web/fetch_product_sku_list', params: ['product_id', 'author_id'] },
  fetchProductCoupon: { path: '/web/fetch_product_coupon', params: ['product_id', 'shop_id', 'price', 'author_id', 'sec_user_id'] },
  fetchProductReviewScore: { path: '/web/fetch_product_review_score', params: ['product_id', 'shop_id'] },
  fetchProductReviewList: { path: '/web/fetch_product_review_list', params: ['product_id', 'shop_id'] },
  fetchUserProfileByUid: { path: '/web/fetch_user_profile_by_uid', params: ['uid'] },
  fetchBatchUserProfileV1: { path: '/web/fetch_batch_user_profile_v1', params: ['sec_user_ids'] },
  fetchBatchUserProfileV2: { path: '/web/fetch_batch_user_profile_v2', params: ['sec_user_ids'] },
  fetchUserLiveInfoByUid: { path: '/web/fetch_user_live_info_by_uid', params: ['uid'] },
  fetchUserProfileByShortId: { path: '/web/fetch_user_profile_by_short_id', params: ['short_id'] },
  handlerShortenUrl: { path: '/web/handler_shorten_url', params: ['target_url'] },
  handlerUserProfileV2: { path: '/web/handler_user_profile_v2', params: ['unique_id'] },
  encryptUidToSecUserId: { path: '/web/encrypt_uid_to_sec_user_id', params: ['uid'] },
  handlerUserProfileV3: { path: '/web/handler_user_profile_v3', params: ['uid'] },
  handlerUserProfileV4: { path: '/web/handler_user_profile_v4', params: ['sec_user_id'] },
  fetchChallengePosts: { path: '/web/fetch_challenge_posts', method: 'POST' },
  fetchVideoChannelResult: { path: '/web/fetch_video_channel_result', params: ['tag_id'] },
  webcastId_2RoomId: { path: '/web/webcast_id_2_room_id', params: ['webcast_id'] },
  fetchLiveImFetch: { path: '/web/fetch_live_im_fetch', params: ['room_id', 'user_unique_id'] },
  fetchSeriesAweme: { path: '/web/fetch_series_aweme', params: ['offset', 'count', 'content_type'] },
  fetchKnowledgeAweme: { path: '/web/fetch_knowledge_aweme', params: ['count'] },
  fetchGameAweme: { path: '/web/fetch_game_aweme', params: ['count'] },
  fetchCartoonAweme: { path: '/web/fetch_cartoon_aweme', params: ['count'] },
  fetchMusicAweme: { path: '/web/fetch_music_aweme', params: ['count'] },
  fetchFoodAweme: { path: '/web/fetch_food_aweme', params: ['count'] },
  fetchLiveGiftRanking: { path: '/web/fetch_live_gift_ranking', params: ['room_id'] },
  fetchUserSearchResultV2: { path: '/web/fetch_user_search_result_v2', params: ['keyword'] },
  fetchUserSearchResultV3: { path: '/web/fetch_user_search_result_v3', params: ['keyword'] },
  fetchSearchChallenge: { path: '/web/fetch_search_challenge', method: 'POST' },
  fetchHotSearchResult: { path: '/web/fetch_hot_search_result' },
  fetchQueryUser: { path: '/web/fetch_query_user', method: 'POST' },
  getSecUserId: { path: '/web/get_sec_user_id', params: ['url'] },
  getAllSecUserId: { path: '/web/get_all_sec_user_id', method: 'POST' },
  getAwemeId: { path: '/web/get_aweme_id', params: ['url'] },
  getAllAwemeId: { path: '/web/get_all_aweme_id', method: 'POST' },
  getWebcastId: { path: '/web/get_webcast_id', params: ['url'] },
  getAllWebcastId: { path: '/web/get_all_webcast_id', method: 'POST' },
  douyinLiveRoom: { path: '/web/douyin_live_room', params: ['live_room_url', 'danmaku_type'] },
  // app/v3
  fetchOneVideo: { path: '/app/v3/fetch_one_video', params: ['aweme_id'] },
  fetchOneVideoV2: { path: '/app/v3/fetch_one_video_v2', params: ['aweme_id'] },
  fetchOneVideoV3: { path: '/app/v3/fetch_one_video_v3', params: ['aweme_id'] },
  fetchShareInfoByShareCode: { path: '/app/v3/fetch_share_info_by_share_code', params: ['share_code'] },
  fetchMultiVideo: { path: '/app/v3/fetch_multi_video', method: 'POST' },
  fetchMultiVideoV2: { path: '/app/v3/fetch_multi_video_v2', method: 'POST' },
  fetchOneVideoByShareUrl: { path: '/app/v3/fetch_one_video_by_share_url', params: ['share_url'] },
  fetchVideoHighQualityPlayUrl: { path: '/app/v3/fetch_video_high_quality_play_url' },
  fetchMultiVideoHighQualityPlayUrl: { path: '/app/v3/fetch_multi_video_high_quality_play_url', method: 'POST' },
  handlerUserProfile: { path: '/app/v3/handler_user_profile', params: ['sec_user_id'] },
  fetchUserFansList: { path: '/app/v3/fetch_user_fans_list' },
  fetchUserPostVideos: { path: '/app/v3/fetch_user_post_videos', params: ['sec_user_id'] },
  fetchVideoMixDetail: { path: '/app/v3/fetch_video_mix_detail', params: ['mix_id'] },
  fetchVideoMixPostList: { path: '/app/v3/fetch_video_mix_post_list', params: ['mix_id'] },
  fetchUserSeriesList: { path: '/app/v3/fetch_user_series_list' },
  fetchSeriesVideoList: { path: '/app/v3/fetch_series_video_list', params: ['series_id'] },
  fetchSeriesDetail: { path: '/app/v3/fetch_series_detail', params: ['series_id'] },
  fetchMusicDetail: { path: '/app/v3/fetch_music_detail', params: ['music_id'] },
  fetchMusicVideoList: { path: '/app/v3/fetch_music_video_list', params: ['music_id'] },
  fetchHashtagDetail: { path: '/app/v3/fetch_hashtag_detail', params: ['ch_id'] },
  fetchHashtagVideoList: { path: '/app/v3/fetch_hashtag_video_list', params: ['ch_id'] },
  fetchVideoStatistics: { path: '/app/v3/fetch_video_statistics', params: ['aweme_ids'] },
  fetchMultiVideoStatistics: { path: '/app/v3/fetch_multi_video_statistics', params: ['aweme_ids'] },
  fetchUserFollowingList: { path: '/app/v3/fetch_user_following_list' },
  fetchUserLikeVideos: { path: '/app/v3/fetch_user_like_videos', params: ['sec_user_id'] },
  fetchVideoComments: { path: '/app/v3/fetch_video_comments', params: ['aweme_id'] },
  fetchVideoCommentReplies: { path: '/app/v3/fetch_video_comment_replies', params: ['item_id', 'comment_id'] },
  fetchGeneralSearchResult: { path: '/app/v3/fetch_general_search_result', params: ['keyword'] },
  fetchVideoSearchResult: { path: '/app/v3/fetch_video_search_result', params: ['keyword'] },
  fetchVideoSearchResultV2: { path: '/app/v3/fetch_video_search_result_v2', params: ['keyword'] },
  fetchUserSearchResult: { path: '/app/v3/fetch_user_search_result', params: ['keyword'] },
  fetchLiveSearchResult: { path: '/app/v3/fetch_live_search_result', params: ['keyword'] },
  fetchMusicSearchResult: { path: '/app/v3/fetch_music_search_result', params: ['keyword'] },
  fetchHashtagSearchResult: { path: '/app/v3/fetch_hashtag_search_result', params: ['keyword'] },
  fetchHotSearchList: { path: '/app/v3/fetch_hot_search_list' },
  fetchLiveHotSearchList: { path: '/app/v3/fetch_live_hot_search_list' },
  fetchMusicHotSearchList: { path: '/app/v3/fetch_music_hot_search_list' },
  fetchBrandHotSearchList: { path: '/app/v3/fetch_brand_hot_search_list' },
  fetchBrandHotSearchListDetail: { path: '/app/v3/fetch_brand_hot_search_list_detail', params: ['category_id'] },
  openDouyinAppToKeywordSearch: { path: '/app/v3/open_douyin_app_to_keyword_search', params: ['keyword'] },
  generateDouyinShortUrl: { path: '/app/v3/generate_douyin_short_url', params: ['url'] },
  generateDouyinVideoShareQrcode: { path: '/app/v3/generate_douyin_video_share_qrcode', params: ['object_id'] },
  openDouyinAppToVideoDetail: { path: '/app/v3/open_douyin_app_to_video_detail', params: ['aweme_id'] },
  openDouyinAppToUserProfile: { path: '/app/v3/open_douyin_app_to_user_profile', params: ['uid', 'sec_uid'] },
  openDouyinAppToSendPrivateMessage: { path: '/app/v3/open_douyin_app_to_send_private_message', params: ['uid', 'sec_uid'] },
  // creator
  fetchCreatorMaterialCenterBillboard: { path: '/creator/fetch_creator_material_center_billboard' },
  fetchCreatorHotSpotBillboard: { path: '/creator/fetch_creator_hot_spot_billboard' },
  fetchCreatorHotTopicBillboard: { path: '/creator/fetch_creator_hot_topic_billboard' },
  fetchCreatorHotPropsBillboard: { path: '/creator/fetch_creator_hot_props_billboard' },
  fetchCreatorHotChallengeBillboard: { path: '/creator/fetch_creator_hot_challenge_billboard' },
  fetchCreatorHotMusicBillboard: { path: '/creator/fetch_creator_hot_music_billboard' },
  fetchCreatorActivityList: { path: '/creator/fetch_creator_activity_list', params: ['start_time', 'end_time'] },
  fetchCreatorActivityDetail: { path: '/creator/fetch_creator_activity_detail', params: ['activity_id'] },
  fetchCreatorMaterialCenterConfig: { path: '/creator/fetch_creator_material_center_config' },
  fetchCreatorHotCourse: { path: '/creator/fetch_creator_hot_course' },
  fetchCreatorContentCategory: { path: '/creator/fetch_creator_content_category' },
  fetchCreatorContentCourse: { path: '/creator/fetch_creator_content_course', params: ['category_id'] },
  fetchVideoDanmakuList: { path: '/creator/fetch_video_danmaku_list', params: ['item_id'] },
  fetchMissionTaskList: { path: '/creator/fetch_mission_task_list' },
  fetchIndustryCategoryConfig: { path: '/creator/fetch_industry_category_config' },
  // creator_v2
  fetchItemPlaySource: { path: '/creator_v2/fetch_item_play_source', method: 'POST' },
  fetchItemWatchTrend: { path: '/creator_v2/fetch_item_watch_trend', method: 'POST' },
  fetchItemDanmakuAnalysis: { path: '/creator_v2/fetch_item_danmaku_analysis', method: 'POST' },
  fetchItemAudiencePortrait: { path: '/creator_v2/fetch_item_audience_portrait', method: 'POST' },
  fetchItemAudienceOthers: { path: '/creator_v2/fetch_item_audience_others', method: 'POST' },
  fetchItemAnalysisOverview: { path: '/creator_v2/fetch_item_analysis_overview', method: 'POST' },
  fetchItemSearchKeyword: { path: '/creator_v2/fetch_item_search_keyword', method: 'POST' },
  fetchItemOverviewData: { path: '/creator_v2/fetch_item_overview_data', method: 'POST' },
  fetchItemAnalysisInvolvedVertical: { path: '/creator_v2/fetch_item_analysis_involved_vertical', method: 'POST' },
  fetchItemAnalysisItemPerformance: { path: '/creator_v2/fetch_item_analysis_item_performance', method: 'POST' },
  fetchItemList: { path: '/creator_v2/fetch_item_list', method: 'POST' },
  fetchItemListDownload: { path: '/creator_v2/fetch_item_list_download', method: 'POST' },
  fetchLiveRoomHistoryList: { path: '/creator_v2/fetch_live_room_history_list', method: 'POST' },
  fetchAuthorDiagnosis: { path: '/creator_v2/fetch_author_diagnosis', method: 'POST' },
  // index
  fetchAllValidDate: { path: '/index/fetch_all_valid_date' },
  fetchValidDateForRelation: { path: '/index/fetch_valid_date_for_relation' },
  fetchAllArea: { path: '/index/fetch_all_area' },
  fetchCurrentHotTopic: { path: '/index/fetch_current_hot_topic' },
  fetchHotWords: { path: '/index/fetch_hot_words' },
  fetchKeywordValidDate: { path: '/index/fetch_keyword_valid_date', params: ['keyword_list'], method: 'POST' },
  fetchMultiKeywordHotTrend: { path: '/index/fetch_multi_keyword_hot_trend', params: ['keyword_list', 'start_date', 'end_date'], method: 'POST' },
  fetchMultiKeywordInterpretation: { path: '/index/fetch_multi_keyword_interpretation', params: ['keyword_list', 'start_date', 'end_date'], method: 'POST' },
  fetchRelationWord: { path: '/index/fetch_relation_word', params: ['keyword', 'start_date', 'end_date'], method: 'POST' },
  fetchPortrait: { path: '/index/fetch_portrait', params: ['keyword', 'start_date', 'end_date'], method: 'POST' },
  fetchGetUserSubWord: { path: '/index/fetch_get_user_sub_word', method: 'POST' },
  fetchEncryptUserId: { path: '/index/fetch_encrypt_user_id', params: ['uid'] },
  fetchDarenCompareUsersStable: { path: '/index/fetch_daren_compare_users_stable', params: ['user_list'], method: 'POST' },
  fetchDarenSimilarUsers: { path: '/index/fetch_daren_similar_users', params: ['user_id'], method: 'POST' },
  fetchDarenGreatUserTopVideo: { path: '/index/fetch_daren_great_user_top_video', params: ['user_id', 'start_date', 'end_date'], method: 'POST' },
  fetchDarenGreatItemMileInfo: { path: '/index/fetch_daren_great_item_mile_info', params: ['user_id'], method: 'POST' },
  fetchDarenGreatUserFansInfo: { path: '/index/fetch_daren_great_user_fans_info', params: ['user_id'], method: 'POST' },
  fetchBrandValidInfo: { path: '/index/fetch_brand_valid_info', params: ['keyword_list'], method: 'POST' },
  fetchBrandRadarChart: { path: '/index/fetch_brand_radar_chart', params: ['brand_name', 'start_date', 'end_date'], method: 'POST' },
  fetchBrandLines: { path: '/index/fetch_brand_lines', params: ['brand_name', 'start_date', 'end_date'], method: 'POST' },
  fetchBrandCycles: { path: '/index/fetch_brand_cycles', params: ['brand_name', 'start_date', 'end_date'], method: 'POST' },
  fetchBrandInitiativeRankWeekly: { path: '/index/fetch_brand_initiative_rank_weekly', params: ['brand_name', 'start_date', 'end_date'], method: 'POST' },
  fetchContentValidDate: { path: '/index/fetch_content_valid_date' },
  fetchBrandHotVideosTimeScope: { path: '/index/fetch_brand_hot_videos_time_scope', method: 'POST' },
  fetchContentCreativeKeywords: { path: '/index/fetch_content_creative_keywords', params: ['tag_id', 'end_date'], method: 'POST' },
  fetchContentCreativeKeywordItems: { path: '/index/fetch_content_creative_keyword_items', params: ['tag_id', 'end_date', 'keyword'], method: 'POST' },
  fetchContentCreativeTopic: { path: '/index/fetch_content_creative_topic', params: ['tag_id', 'end_date'], method: 'POST' },
  fetchContentPublishTrend: { path: '/index/fetch_content_publish_trend', params: ['tag_id', 'start_date', 'end_date'] },
  fetchContentCreativeDuration: { path: '/index/fetch_content_creative_duration', params: ['tag_id', 'end_date'], method: 'POST' },
  fetchContentAuthorPortrait: { path: '/index/fetch_content_author_portrait', params: ['tag_id', 'end_date'], method: 'POST' },
  fetchContentConsumerPortrait: { path: '/index/fetch_content_consumer_portrait', params: ['tag_id', 'end_date'], method: 'POST' },
  fetchContentInteractTrend: { path: '/index/fetch_content_interact_trend', params: ['tag_id', 'start_date', 'end_date'], method: 'POST' },
  fetchContentConsumeTrend: { path: '/index/fetch_content_consume_trend', params: ['tag_id', 'start_date', 'end_date'], method: 'POST' },
  fetchInsightRecommend: { path: '/index/fetch_insight_recommend' },
  fetchReportDetail: { path: '/index/fetch_report_detail', params: ['report_id'] },
  fetchInsightGetRec: { path: '/index/fetch_insight_get_rec', params: ['report_id'] },
  fetchDarenSugGreatUserList: { path: '/index/fetch_daren_sug_great_user_list', params: ['keyword'], method: 'POST' },
  fetchItemFilterOptions: { path: '/index/fetch_item_filter_options' },
  fetchItemSug: { path: '/index/fetch_item_sug', params: ['query'], method: 'POST' },
  fetchItemQuery: { path: '/index/fetch_item_query', params: ['query'], method: 'POST' },
  fetchBrandSuggest: { path: '/index/fetch_brand_suggest', params: ['keyword'], method: 'POST' },
  fetchTopicSuggest: { path: '/index/fetch_topic_suggest', params: ['keyword'], method: 'POST' },
  fetchTopicQuery: { path: '/index/fetch_topic_query', params: ['keyword', 'start_date', 'end_date'], method: 'POST' },
  fetchReportSearch: { path: '/index/fetch_report_search', method: 'POST' },
  // billboard
  fetchCityList: { path: '/billboard/fetch_city_list' },
  fetchContentTag: { path: '/billboard/fetch_content_tag' },
  fetchHotCategoryList: { path: '/billboard/fetch_hot_category_list', params: ['billboard_type'] },
  fetchHotRiseList: { path: '/billboard/fetch_hot_rise_list', params: ['page', 'page_size', 'order'] },
  fetchHotCityList: { path: '/billboard/fetch_hot_city_list', params: ['page', 'page_size', 'order'] },
  fetchHotChallengeList: { path: '/billboard/fetch_hot_challenge_list', params: ['page', 'page_size'] },
  fetchHotTotalList: { path: '/billboard/fetch_hot_total_list', params: ['page', 'page_size', 'type'] },
  fetchHotCalendarList: { path: '/billboard/fetch_hot_calendar_list', method: 'POST' },
  fetchHotCalendarDetail: { path: '/billboard/fetch_hot_calendar_detail', params: ['calendar_id'] },
  fetchHotUserPortraitList: { path: '/billboard/fetch_hot_user_portrait_list', params: ['aweme_id'] },
  fetchHotCommentWordList: { path: '/billboard/fetch_hot_comment_word_list', params: ['aweme_id'] },
  fetchHotItemTrendsList: { path: '/billboard/fetch_hot_item_trends_list' },
  fetchHotAccountList: { path: '/billboard/fetch_hot_account_list', method: 'POST' },
  fetchHotAccountTrendsList: { path: '/billboard/fetch_hot_account_trends_list', params: ['sec_uid'] },
  fetchHotAccountItemAnalysisList: { path: '/billboard/fetch_hot_account_item_analysis_list', params: ['sec_uid'] },
  fetchHotAccountFansPortraitList: { path: '/billboard/fetch_hot_account_fans_portrait_list', params: ['sec_uid'] },
  fetchHotAccountFansInterestAccountList: { path: '/billboard/fetch_hot_account_fans_interest_account_list', params: ['sec_uid'] },
  fetchHotAccountFansInterestTopicList: { path: '/billboard/fetch_hot_account_fans_interest_topic_list', params: ['sec_uid'] },
  fetchHotTotalVideoList: { path: '/billboard/fetch_hot_total_video_list', method: 'POST' },
  fetchHotTotalLowFanList: { path: '/billboard/fetch_hot_total_low_fan_list', method: 'POST' },
  fetchHotTotalHighPlayList: { path: '/billboard/fetch_hot_total_high_play_list', method: 'POST' },
  fetchHotTotalHighLikeList: { path: '/billboard/fetch_hot_total_high_like_list', method: 'POST' },
  fetchHotTotalHighFanList: { path: '/billboard/fetch_hot_total_high_fan_list', method: 'POST' },
  fetchHotTotalTopicList: { path: '/billboard/fetch_hot_total_topic_list', method: 'POST' },
  fetchHotTotalHighTopicList: { path: '/billboard/fetch_hot_total_high_topic_list', method: 'POST' },
  fetchHotTotalHotWordList: { path: '/billboard/fetch_hot_total_hot_word_list', method: 'POST' },
  fetchHotTotalHotWordDetailList: { path: '/billboard/fetch_hot_total_hot_word_detail_list', params: ['keyword', 'word_id', 'query_day'] },
  fetchHotAccountSearchList: { path: '/billboard/fetch_hot_account_search_list', params: ['keyword', 'cursor'] },
  fetchHotAccountFansInterestSearchList: { path: '/billboard/fetch_hot_account_fans_interest_search_list', params: ['sec_uid'] },
  fetchHotTotalSearchList: { path: '/billboard/fetch_hot_total_search_list', method: 'POST' },
  fetchHotTotalHighSearchList: { path: '/billboard/fetch_hot_total_high_search_list', method: 'POST' },
  // xingtu
  kolConversionAbilityAnalysisV1: { path: '/xingtu/kol_conversion_ability_analysis_v1', params: ['kolId', '_range'] },
  kolXingtuIndexV1: { path: '/xingtu/kol_xingtu_index_v1', params: ['kolId'] },
  kolCpInfoV1: { path: '/xingtu/kol_cp_info_v1', params: ['kolId'] },
  authorHotCommentTokensV1: { path: '/xingtu/author_hot_comment_tokens_v1', params: ['kolId'] },
  authorContentHotCommentKeywordsV1: { path: '/xingtu/author_content_hot_comment_keywords_v1', params: ['kolId'] },
  searchKolV1: { path: '/xingtu/search_kol_v1', params: ['keyword', 'platformSource', 'page'] },
  searchKolV2: { path: '/xingtu/search_kol_v2', params: ['keyword'] },
  getSignImage: { path: '/xingtu/get_sign_image', params: ['uri'] },
  getXingtuKolidByUid: { path: '/xingtu/get_xingtu_kolid_by_uid', params: ['uid'] },
  getXingtuKolidBySecUserId: { path: '/xingtu/get_xingtu_kolid_by_sec_user_id', params: ['sec_user_id'] },
  getXingtuKolidByUniqueId: { path: '/xingtu/get_xingtu_kolid_by_unique_id', params: ['unique_id'] },
  kolBaseInfoV1: { path: '/xingtu/kol_base_info_v1', params: ['kolId', 'platformChannel'] },
  kolAudiencePortraitV1: { path: '/xingtu/kol_audience_portrait_v1', params: ['kolId'] },
  kolFansPortraitV1: { path: '/xingtu/kol_fans_portrait_v1', params: ['kolId'] },
  kolServicePriceV1: { path: '/xingtu/kol_service_price_v1', params: ['kolId', 'platformChannel'] },
  kolDataOverviewV1: { path: '/xingtu/kol_data_overview_v1', params: ['kolId', '_type', '_range', 'flowType'] },
  kolVideoPerformanceV1: { path: '/xingtu/kol_video_performance_v1', params: ['kolId', 'onlyAssign'] },
  kolConvertVideoDisplayV1: { path: '/xingtu/kol_convert_video_display_v1', params: ['kolId', 'detailType', 'page'] },
  kolLinkStructV1: { path: '/xingtu/kol_link_struct_v1', params: ['kolId'] },
  kolTouchDistributionV1: { path: '/xingtu/kol_touch_distribution_v1', params: ['kolId'] },
  kolRecVideosV1: { path: '/xingtu/kol_rec_videos_v1', params: ['kolId'] },
  kolDailyFansV1: { path: '/xingtu/kol_daily_fans_v1', params: ['kolId', 'startDate', 'endDate'] },
  // xingtu_v2
  getRankingListCatalog: { path: '/xingtu_v2/get_ranking_list_catalog' },
  getRankingListData: { path: '/xingtu_v2/get_ranking_list_data' },
  getPlayletActorRankCatalog: { path: '/xingtu_v2/get_playlet_actor_rank_catalog', method: 'POST' },
  getPlayletActorRankList: { path: '/xingtu_v2/get_playlet_actor_rank_list' },
  getContentTrendGuide: { path: '/xingtu_v2/get_content_trend_guide' },
  getDemanderMcnList: { path: '/xingtu_v2/get_demander_mcn_list' },
  getAuthorMarketFields: { path: '/xingtu_v2/get_author_market_fields' },
  getAuthorBaseInfo: { path: '/xingtu_v2/get_author_base_info', params: ['o_author_id'] },
  getAuthorBusinessCardInfo: { path: '/xingtu_v2/get_author_business_card_info', params: ['o_author_id'] },
  getAuthorLocalInfo: { path: '/xingtu_v2/get_author_local_info', params: ['o_author_id'] },
  getAuthorShowItems: { path: '/xingtu_v2/get_author_show_items', params: ['o_author_id'] },
  getAuthorHotCommentTokens: { path: '/xingtu_v2/get_author_hot_comment_tokens', params: ['author_id'] },
  getAuthorContentHotKeywords: { path: '/xingtu_v2/get_author_content_hot_keywords', params: ['author_id'] },
  getRecommendForStarAuthors: { path: '/xingtu_v2/get_recommend_for_star_authors', method: 'POST' },
  getExcellentCaseCategoryList: { path: '/xingtu_v2/get_excellent_case_category_list' },
  getAuthorSpreadInfo: { path: '/xingtu_v2/get_author_spread_info', params: ['o_author_id'] },
  getUserProfileQrcode: { path: '/xingtu_v2/get_user_profile_qrcode' },
  getIpActivityIndustryList: { path: '/xingtu_v2/get_ip_activity_industry_list' },
  getIpActivityList: { path: '/xingtu_v2/get_ip_activity_list', method: 'POST' },
  getIpActivityDetail: { path: '/xingtu_v2/get_ip_activity_detail', params: ['id'] },
  getResourceList: { path: '/xingtu_v2/get_resource_list', params: ['resource_id'] },
  // search
  fetchGeneralSearchV1: { path: '/search/fetch_general_search_v1', method: 'POST' },
  fetchGeneralSearchV2: { path: '/search/fetch_general_search_v2', method: 'POST' },
  fetchSearchSuggest: { path: '/search/fetch_search_suggest', method: 'POST' },
  fetchVideoSearchV1: { path: '/search/fetch_video_search_v1', method: 'POST' },
  fetchVideoSearchV2: { path: '/search/fetch_video_search_v2', method: 'POST' },
  fetchMultiSearch: { path: '/search/fetch_multi_search', method: 'POST' },
  fetchUserSearch: { path: '/search/fetch_user_search', method: 'POST' },
  fetchUserSearchV2: { path: '/search/fetch_user_search_v2', method: 'POST' },
  fetchImageSearch: { path: '/search/fetch_image_search', method: 'POST' },
  fetchImageSearchV3: { path: '/search/fetch_image_search_v3', method: 'POST' },
  fetchLiveSearchV1: { path: '/search/fetch_live_search_v1', method: 'POST' },
  fetchChallengeSearchV1: { path: '/search/fetch_challenge_search_v1', method: 'POST' },
  fetchChallengeSearchV2: { path: '/search/fetch_challenge_search_v2', method: 'POST' },
  fetchChallengeSuggest: { path: '/search/fetch_challenge_suggest', method: 'POST' },
  fetchExperienceSearch: { path: '/search/fetch_experience_search', method: 'POST' },
  fetchMusicSearch: { path: '/search/fetch_music_search', method: 'POST' },
  fetchDiscussSearch: { path: '/search/fetch_discuss_search', method: 'POST' },
  fetchSchoolSearch: { path: '/search/fetch_school_search', method: 'POST' },
  fetchVisionSearch: { path: '/search/fetch_vision_search', method: 'POST' },
};

/**
 * 通用API调用方法
 * 根据API注册表动态调用，替代重复的函数定义
 * @param {string} apiName - 注册表中的API名称
 * @param {object} params - 请求参数
 * @returns {Promise<object>} API响应数据
 */
async function callApi(apiName, params = {}) {
  const def = API_REGISTRY[apiName];
  if (!def) throw new Error(`未知的API: ${apiName}`);
  const reqParams = {};
  if (def.params) {
    for (const key of def.params) {
      if (params[key] !== undefined) reqParams[key] = params[key];
    }
  }
  Object.assign(reqParams, params);
  return request(def.path, reqParams, def.method || 'GET');
}

/**
 * 批量生成API调用函数
 * 从注册表自动生成所有API的便捷调用方法
 */
const api = {};
for (const [name, def] of Object.entries(API_REGISTRY)) {
  api[name] = async (...args) => {
    const params = {};
    if (def.params) {
      for (let i = 0; i < def.params.length; i++) {
        if (args[i] !== undefined) params[def.params[i]] = args[i];
      }
    }
    if (args.length > 0 && typeof args[args.length - 1] === 'object' && !Array.isArray(args[args.length - 1])) {
      Object.assign(params, args[args.length - 1]);
    }
    return request(def.path, params, def.method || 'GET');
  };
}
module.exports = {
  request,
  callApi,
  API_REGISTRY,
  fetchOneVideoDanmaku: api.fetchOneVideoDanmaku,
  fetchHomeFeed: api.fetchHomeFeed,
  fetchRelatedPosts: api.fetchRelatedPosts,
  fetchUserCollectionVideos: api.fetchUserCollectionVideos,
  fetchUserCollects: api.fetchUserCollects,
  fetchUserCollectsVideos: api.fetchUserCollectsVideos,
  fetchUserMixVideos: api.fetchUserMixVideos,
  fetchUserLiveVideos: api.fetchUserLiveVideos,
  fetchUserLiveVideosBySecUid: api.fetchUserLiveVideosBySecUid,
  fetchUserLiveVideosByRoomId: api.fetchUserLiveVideosByRoomId,
  fetchUserLiveVideosByRoomIdV2: api.fetchUserLiveVideosByRoomIdV2,
  fetchLiveRoomProductResult: api.fetchLiveRoomProductResult,
  fetchProductDetail: api.fetchProductDetail,
  fetchProductSkuList: api.fetchProductSkuList,
  fetchProductCoupon: api.fetchProductCoupon,
  fetchProductReviewScore: api.fetchProductReviewScore,
  fetchProductReviewList: api.fetchProductReviewList,
  fetchUserProfileByUid: api.fetchUserProfileByUid,
  fetchBatchUserProfileV1: api.fetchBatchUserProfileV1,
  fetchBatchUserProfileV2: api.fetchBatchUserProfileV2,
  fetchUserLiveInfoByUid: api.fetchUserLiveInfoByUid,
  fetchUserProfileByShortId: api.fetchUserProfileByShortId,
  handlerShortenUrl: api.handlerShortenUrl,
  handlerUserProfileV2: api.handlerUserProfileV2,
  encryptUidToSecUserId: api.encryptUidToSecUserId,
  handlerUserProfileV3: api.handlerUserProfileV3,
  handlerUserProfileV4: api.handlerUserProfileV4,
  fetchChallengePosts: api.fetchChallengePosts,
  fetchVideoChannelResult: api.fetchVideoChannelResult,
  webcastId_2RoomId: api.webcastId_2RoomId,
  fetchLiveImFetch: api.fetchLiveImFetch,
  fetchSeriesAweme: api.fetchSeriesAweme,
  fetchKnowledgeAweme: api.fetchKnowledgeAweme,
  fetchGameAweme: api.fetchGameAweme,
  fetchCartoonAweme: api.fetchCartoonAweme,
  fetchMusicAweme: api.fetchMusicAweme,
  fetchFoodAweme: api.fetchFoodAweme,
  fetchOneVideo: api.fetchOneVideo,
  fetchOneVideoV2: api.fetchOneVideoV2,
  fetchOneVideoV3: api.fetchOneVideoV3,
  fetchShareInfoByShareCode: api.fetchShareInfoByShareCode,
  fetchMultiVideo: api.fetchMultiVideo,
  fetchMultiVideoV2: api.fetchMultiVideoV2,
  fetchOneVideoByShareUrl: api.fetchOneVideoByShareUrl,
  fetchVideoHighQualityPlayUrl: api.fetchVideoHighQualityPlayUrl,
  fetchMultiVideoHighQualityPlayUrl: api.fetchMultiVideoHighQualityPlayUrl,
  handlerUserProfile: api.handlerUserProfile,
  fetchUserFansList: api.fetchUserFansList,
  fetchUserPostVideos: api.fetchUserPostVideos,
  fetchVideoMixDetail: api.fetchVideoMixDetail,
  fetchVideoMixPostList: api.fetchVideoMixPostList,
  fetchUserSeriesList: api.fetchUserSeriesList,
  fetchSeriesVideoList: api.fetchSeriesVideoList,
  fetchSeriesDetail: api.fetchSeriesDetail,
  fetchMusicDetail: api.fetchMusicDetail,
  fetchMusicVideoList: api.fetchMusicVideoList,
  fetchHashtagDetail: api.fetchHashtagDetail,
  fetchHashtagVideoList: api.fetchHashtagVideoList,
  fetchLiveGiftRanking: api.fetchLiveGiftRanking,
  fetchVideoStatistics: api.fetchVideoStatistics,
  fetchMultiVideoStatistics: api.fetchMultiVideoStatistics,
  fetchCreatorMaterialCenterBillboard: api.fetchCreatorMaterialCenterBillboard,
  fetchCreatorHotSpotBillboard: api.fetchCreatorHotSpotBillboard,
  fetchCreatorHotTopicBillboard: api.fetchCreatorHotTopicBillboard,
  fetchCreatorHotPropsBillboard: api.fetchCreatorHotPropsBillboard,
  fetchCreatorHotChallengeBillboard: api.fetchCreatorHotChallengeBillboard,
  fetchCreatorHotMusicBillboard: api.fetchCreatorHotMusicBillboard,
  fetchItemPlaySource: api.fetchItemPlaySource,
  fetchItemWatchTrend: api.fetchItemWatchTrend,
  fetchItemDanmakuAnalysis: api.fetchItemDanmakuAnalysis,
  fetchItemAudiencePortrait: api.fetchItemAudiencePortrait,
  fetchItemAudienceOthers: api.fetchItemAudienceOthers,
  fetchItemAnalysisOverview: api.fetchItemAnalysisOverview,
  fetchAllValidDate: api.fetchAllValidDate,
  fetchValidDateForRelation: api.fetchValidDateForRelation,
  fetchAllArea: api.fetchAllArea,
  fetchCurrentHotTopic: api.fetchCurrentHotTopic,
  fetchHotWords: api.fetchHotWords,
  fetchKeywordValidDate: api.fetchKeywordValidDate,
  fetchMultiKeywordHotTrend: api.fetchMultiKeywordHotTrend,
  fetchMultiKeywordInterpretation: api.fetchMultiKeywordInterpretation,
  fetchRelationWord: api.fetchRelationWord,
  fetchPortrait: api.fetchPortrait,
  fetchGetUserSubWord: api.fetchGetUserSubWord,
  fetchEncryptUserId: api.fetchEncryptUserId,
  fetchDarenCompareUsersStable: api.fetchDarenCompareUsersStable,
  fetchDarenSimilarUsers: api.fetchDarenSimilarUsers,
  fetchDarenGreatUserTopVideo: api.fetchDarenGreatUserTopVideo,
  fetchDarenGreatItemMileInfo: api.fetchDarenGreatItemMileInfo,
  fetchDarenGreatUserFansInfo: api.fetchDarenGreatUserFansInfo,
  fetchBrandValidInfo: api.fetchBrandValidInfo,
  fetchBrandRadarChart: api.fetchBrandRadarChart,
  fetchBrandLines: api.fetchBrandLines,
  fetchBrandCycles: api.fetchBrandCycles,
  fetchBrandInitiativeRankWeekly: api.fetchBrandInitiativeRankWeekly,
  fetchContentValidDate: api.fetchContentValidDate,
  fetchBrandHotVideosTimeScope: api.fetchBrandHotVideosTimeScope,
  fetchContentCreativeKeywords: api.fetchContentCreativeKeywords,
  fetchContentCreativeKeywordItems: api.fetchContentCreativeKeywordItems,
  fetchContentCreativeTopic: api.fetchContentCreativeTopic,
  fetchContentPublishTrend: api.fetchContentPublishTrend,
  fetchContentCreativeDuration: api.fetchContentCreativeDuration,
  fetchContentAuthorPortrait: api.fetchContentAuthorPortrait,
  fetchContentConsumerPortrait: api.fetchContentConsumerPortrait,
  fetchContentInteractTrend: api.fetchContentInteractTrend,
  fetchContentConsumeTrend: api.fetchContentConsumeTrend,
  fetchInsightRecommend: api.fetchInsightRecommend,
  fetchReportDetail: api.fetchReportDetail,
  fetchInsightGetRec: api.fetchInsightGetRec,
  fetchCityList: api.fetchCityList,
  fetchContentTag: api.fetchContentTag,
  fetchHotCategoryList: api.fetchHotCategoryList,
  fetchHotRiseList: api.fetchHotRiseList,
  fetchHotCityList: api.fetchHotCityList,
  fetchHotChallengeList: api.fetchHotChallengeList,
  fetchHotTotalList: api.fetchHotTotalList,
  fetchHotCalendarList: api.fetchHotCalendarList,
  fetchHotCalendarDetail: api.fetchHotCalendarDetail,
  fetchHotUserPortraitList: api.fetchHotUserPortraitList,
  fetchHotCommentWordList: api.fetchHotCommentWordList,
  fetchHotItemTrendsList: api.fetchHotItemTrendsList,
  fetchHotAccountList: api.fetchHotAccountList,
  fetchHotAccountTrendsList: api.fetchHotAccountTrendsList,
  fetchHotAccountItemAnalysisList: api.fetchHotAccountItemAnalysisList,
  fetchHotAccountFansPortraitList: api.fetchHotAccountFansPortraitList,
  fetchHotAccountFansInterestAccountList: api.fetchHotAccountFansInterestAccountList,
  fetchHotAccountFansInterestTopicList: api.fetchHotAccountFansInterestTopicList,
  fetchHotTotalVideoList: api.fetchHotTotalVideoList,
  fetchHotTotalLowFanList: api.fetchHotTotalLowFanList,
  fetchHotTotalHighPlayList: api.fetchHotTotalHighPlayList,
  fetchHotTotalHighLikeList: api.fetchHotTotalHighLikeList,
  fetchHotTotalHighFanList: api.fetchHotTotalHighFanList,
  fetchHotTotalTopicList: api.fetchHotTotalTopicList,
  fetchHotTotalHighTopicList: api.fetchHotTotalHighTopicList,
  fetchHotTotalHotWordList: api.fetchHotTotalHotWordList,
  fetchHotTotalHotWordDetailList: api.fetchHotTotalHotWordDetailList,
  kolConversionAbilityAnalysisV1: api.kolConversionAbilityAnalysisV1,
  kolXingtuIndexV1: api.kolXingtuIndexV1,
  kolCpInfoV1: api.kolCpInfoV1,
  authorHotCommentTokensV1: api.authorHotCommentTokensV1,
  authorContentHotCommentKeywordsV1: api.authorContentHotCommentKeywordsV1,
  getRankingListCatalog: api.getRankingListCatalog,
  getRankingListData: api.getRankingListData,
  getPlayletActorRankCatalog: api.getPlayletActorRankCatalog,
  getPlayletActorRankList: api.getPlayletActorRankList,
  getContentTrendGuide: api.getContentTrendGuide,
  fetchUserFollowingList: api.fetchUserFollowingList,
  fetchUserLikeVideos: api.fetchUserLikeVideos,
  fetchVideoComments: api.fetchVideoComments,
  fetchVideoCommentReplies: api.fetchVideoCommentReplies,
  fetchUserSearchResultV2: api.fetchUserSearchResultV2,
  fetchUserSearchResultV3: api.fetchUserSearchResultV3,
  fetchSearchChallenge: api.fetchSearchChallenge,
  fetchHotSearchResult: api.fetchHotSearchResult,
  fetchQueryUser: api.fetchQueryUser,
  fetchGeneralSearchResult: api.fetchGeneralSearchResult,
  fetchVideoSearchResult: api.fetchVideoSearchResult,
  fetchVideoSearchResultV2: api.fetchVideoSearchResultV2,
  fetchUserSearchResult: api.fetchUserSearchResult,
  fetchLiveSearchResult: api.fetchLiveSearchResult,
  fetchMusicSearchResult: api.fetchMusicSearchResult,
  fetchHashtagSearchResult: api.fetchHashtagSearchResult,
  fetchHotSearchList: api.fetchHotSearchList,
  fetchLiveHotSearchList: api.fetchLiveHotSearchList,
  fetchMusicHotSearchList: api.fetchMusicHotSearchList,
  fetchBrandHotSearchList: api.fetchBrandHotSearchList,
  fetchBrandHotSearchListDetail: api.fetchBrandHotSearchListDetail,
  openDouyinAppToKeywordSearch: api.openDouyinAppToKeywordSearch,
  fetchItemSearchKeyword: api.fetchItemSearchKeyword,
  fetchDarenSugGreatUserList: api.fetchDarenSugGreatUserList,
  fetchItemFilterOptions: api.fetchItemFilterOptions,
  fetchItemSug: api.fetchItemSug,
  fetchItemQuery: api.fetchItemQuery,
  fetchBrandSuggest: api.fetchBrandSuggest,
  fetchTopicSuggest: api.fetchTopicSuggest,
  fetchTopicQuery: api.fetchTopicQuery,
  fetchReportSearch: api.fetchReportSearch,
  fetchGeneralSearchV1: api.fetchGeneralSearchV1,
  fetchGeneralSearchV2: api.fetchGeneralSearchV2,
  fetchSearchSuggest: api.fetchSearchSuggest,
  fetchVideoSearchV1: api.fetchVideoSearchV1,
  fetchVideoSearchV2: api.fetchVideoSearchV2,
  fetchMultiSearch: api.fetchMultiSearch,
  fetchUserSearch: api.fetchUserSearch,
  fetchUserSearchV2: api.fetchUserSearchV2,
  fetchImageSearch: api.fetchImageSearch,
  fetchImageSearchV3: api.fetchImageSearchV3,
  fetchLiveSearchV1: api.fetchLiveSearchV1,
  fetchChallengeSearchV1: api.fetchChallengeSearchV1,
  fetchChallengeSearchV2: api.fetchChallengeSearchV2,
  fetchChallengeSuggest: api.fetchChallengeSuggest,
  fetchExperienceSearch: api.fetchExperienceSearch,
  fetchMusicSearch: api.fetchMusicSearch,
  fetchDiscussSearch: api.fetchDiscussSearch,
  fetchSchoolSearch: api.fetchSchoolSearch,
  fetchVisionSearch: api.fetchVisionSearch,
  fetchHotAccountSearchList: api.fetchHotAccountSearchList,
  fetchHotAccountFansInterestSearchList: api.fetchHotAccountFansInterestSearchList,
  fetchHotTotalSearchList: api.fetchHotTotalSearchList,
  fetchHotTotalHighSearchList: api.fetchHotTotalHighSearchList,
  searchKolV1: api.searchKolV1,
  searchKolV2: api.searchKolV2,
  getDemanderMcnList: api.getDemanderMcnList,
  generateDouyinShortUrl: api.generateDouyinShortUrl,
  generateDouyinVideoShareQrcode: api.generateDouyinVideoShareQrcode,
  openDouyinAppToVideoDetail: api.openDouyinAppToVideoDetail,
  openDouyinAppToUserProfile: api.openDouyinAppToUserProfile,
  openDouyinAppToSendPrivateMessage: api.openDouyinAppToSendPrivateMessage,
  getSecUserId: api.getSecUserId,
  getAllSecUserId: api.getAllSecUserId,
  getAwemeId: api.getAwemeId,
  getAllAwemeId: api.getAllAwemeId,
  getWebcastId: api.getWebcastId,
  getAllWebcastId: api.getAllWebcastId,
  douyinLiveRoom: api.douyinLiveRoom,
  fetchCreatorActivityList: api.fetchCreatorActivityList,
  fetchCreatorActivityDetail: api.fetchCreatorActivityDetail,
  fetchCreatorMaterialCenterConfig: api.fetchCreatorMaterialCenterConfig,
  fetchCreatorHotCourse: api.fetchCreatorHotCourse,
  fetchCreatorContentCategory: api.fetchCreatorContentCategory,
  fetchCreatorContentCourse: api.fetchCreatorContentCourse,
  fetchVideoDanmakuList: api.fetchVideoDanmakuList,
  fetchMissionTaskList: api.fetchMissionTaskList,
  fetchIndustryCategoryConfig: api.fetchIndustryCategoryConfig,
  fetchItemOverviewData: api.fetchItemOverviewData,
  fetchItemAnalysisInvolvedVertical: api.fetchItemAnalysisInvolvedVertical,
  fetchItemAnalysisItemPerformance: api.fetchItemAnalysisItemPerformance,
  fetchItemList: api.fetchItemList,
  fetchItemListDownload: api.fetchItemListDownload,
  fetchLiveRoomHistoryList: api.fetchLiveRoomHistoryList,
  fetchAuthorDiagnosis: api.fetchAuthorDiagnosis,
  getSignImage: api.getSignImage,
  getXingtuKolidByUid: api.getXingtuKolidByUid,
  getXingtuKolidBySecUserId: api.getXingtuKolidBySecUserId,
  getXingtuKolidByUniqueId: api.getXingtuKolidByUniqueId,
  kolBaseInfoV1: api.kolBaseInfoV1,
  kolAudiencePortraitV1: api.kolAudiencePortraitV1,
  kolFansPortraitV1: api.kolFansPortraitV1,
  kolServicePriceV1: api.kolServicePriceV1,
  kolDataOverviewV1: api.kolDataOverviewV1,
  kolVideoPerformanceV1: api.kolVideoPerformanceV1,
  kolConvertVideoDisplayV1: api.kolConvertVideoDisplayV1,
  kolLinkStructV1: api.kolLinkStructV1,
  kolTouchDistributionV1: api.kolTouchDistributionV1,
  kolRecVideosV1: api.kolRecVideosV1,
  kolDailyFansV1: api.kolDailyFansV1,
  getAuthorMarketFields: api.getAuthorMarketFields,
  getAuthorBaseInfo: api.getAuthorBaseInfo,
  getAuthorBusinessCardInfo: api.getAuthorBusinessCardInfo,
  getAuthorLocalInfo: api.getAuthorLocalInfo,
  getAuthorShowItems: api.getAuthorShowItems,
  getAuthorHotCommentTokens: api.getAuthorHotCommentTokens,
  getAuthorContentHotKeywords: api.getAuthorContentHotKeywords,
  getRecommendForStarAuthors: api.getRecommendForStarAuthors,
  getExcellentCaseCategoryList: api.getExcellentCaseCategoryList,
  getAuthorSpreadInfo: api.getAuthorSpreadInfo,
  getUserProfileQrcode: api.getUserProfileQrcode,
  getIpActivityIndustryList: api.getIpActivityIndustryList,
  getIpActivityList: api.getIpActivityList,
  getIpActivityDetail: api.getIpActivityDetail,
  getResourceList: api.getResourceList,
};
